name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'   # runs every hour, you can make it daily with '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/@phoenixarjun007"
