name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'   # every hour, change to '0 0 * * *' for daily
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@phoenixarjun007,https://dev.to/feed/naresh_007"
